#!/bin/bash -eu

if [ `cat ./version` != `cat ./tmp/version` ]
then
  echo "Data files out of date, please run ./make-data-files";
  exit 1;
fi

docker-machine start default || echo "Machine is already running";

./docker-init-druid
./docker-init-mysql
./docker-init-postgres
# ./docker-init-presto
