#!/bin/bash -eu

echo "Set Druid props ";

perl -pi -e's/druid.extensions.loadList=.*/druid.extensions.loadList=["druid-lookups-cached-global", "druid-histogram", "druid-datasketches"]/g' \
  /root/imply-*/conf-quickstart/druid/_common/common.runtime.properties
