#!/bin/bash -eu

echo "Sleep for 15 seconds to make sure the server starts";
sleep 15;

echo "Adding Timezone info...";
mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql

echo "Setting up MySQL...";
mysql -u root -e "CREATE DATABASE IF NOT EXISTS datazoo CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

echo "Creating table...";
mysql -u root datazoo < /opt/data/mysql/wikipedia-create-raw-table.sql;

echo "Importing data...";
mysql -u root --default_character_set utf8mb4 datazoo < /opt/data/tmp/wikipedia-raw-mysql.sql;

echo "Rolling up...";
mysql -u root datazoo < /opt/data/mysql/wikipedia-rollup.sql;

echo "Done";
