DROP TABLE IF EXISTS `wikipedia_raw`;
CREATE TABLE `wikipedia_raw` (
  `time` datetime NOT NULL,
  `sometimeLater` timestamp NOT NULL,
  `channel` varchar(255) NOT NULL,
  `cityName` varchar(255) DEFAULT NULL,
  `comment` varchar(300) NOT NULL,
  `commentLength` int(11) NOT NULL,
  `countryIsoCode` varchar(255) DEFAULT NULL,
  `countryName` varchar(255) DEFAULT NULL,
  `isAnonymous` tinyint(1) NOT NULL,
  `isMinor` tinyint(1) NOT NULL,
  `isNew` tinyint(1) NOT NULL,
  `isRobot` tinyint(1) NOT NULL,
  `isUnpatrolled` tinyint(1) NOT NULL,
  `metroCode` int(11) DEFAULT NULL,
  `namespace` varchar(255) DEFAULT NULL,
  `page` varchar(255) DEFAULT NULL,
  `regionIsoCode` varchar(255) DEFAULT NULL,
  `regionName` varchar(255) DEFAULT NULL,
  `user` varchar(255) DEFAULT NULL,
  `delta` int(11) NOT NULL,
  `added` int(11) NOT NULL,
  `deleted` int(11) NOT NULL,
  `deltaByTen` float NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
