#!/bin/bash -eu

echo "Sleep for 5 seconds to make sure the server starts";
sleep 5;

echo "Creating database...";
echo "CREATE DATABASE datazoo;" | psql -q;

echo "Creating table...";
psql -d datazoo -q < /opt/data/postgres/wikipedia-create-raw-table.sql;

echo "Importing data...";
psql -d datazoo -q < /opt/data/tmp/wikipedia-raw-postgres.sql;

echo "Rolling up...";
psql -d datazoo -q < /opt/data/postgres/wikipedia-rollup.sql;

echo "Done";
