DROP TABLE IF EXISTS wikipedia_raw;
CREATE TABLE wikipedia_raw (
  "time" timestamp NOT NULL,
  "sometimeLater" timestamp NOT NULL,
  "channel" varchar(255) COLLATE "C" NOT NULL,
  "cityName" varchar(255) COLLATE "C" DEFAULT NULL,
  "comment" varchar(300) COLLATE "C" NOT NULL,
  "commentLength" int NOT NULL,
  "countryIsoCode" varchar(255) COLLATE "C" DEFAULT NULL,
  "countryName" varchar(255) COLLATE "C" DEFAULT NULL,
  "deltaBucket100" int NOT NULL,
  "isAnonymous" boolean NOT NULL,
  "isMinor" boolean NOT NULL,
  "isNew" boolean NOT NULL,
  "isRobot" boolean NOT NULL,
  "isUnpatrolled" boolean NOT NULL,
  "metroCode" int DEFAULT NULL,
  "namespace" varchar(255) COLLATE "C" DEFAULT NULL,
  "page" varchar(255) COLLATE "C" DEFAULT NULL,
  "regionIsoCode" varchar(255) COLLATE "C" DEFAULT NULL,
  "regionName" varchar(255) COLLATE "C" DEFAULT NULL,
  "user" varchar(255) COLLATE "C" DEFAULT NULL,
  "userChars" char[] DEFAULT NULL,
  "delta" int NOT NULL,
  "added" int NOT NULL,
  "deleted" int NOT NULL,
  "deltaByTen" float NOT NULL
);
